### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by shubhra14** [funkhaus/stackhaus#2]
Is there some documentation for this? This looks very interesting but I am a beginner and need some guidance. The docs on vuehaus is pretty detailed and gave me a good starting point.

**Comment by drewbaker** [comment]
Well mostly this is just Nuxt, so their documentation is largely what you’ll need, along with the Nuxt-Apollo documentation for the Graph QL queries to WordPress. There are a few specific things we are doing to make things easier that I can write up later this week. Mostly those related to the files in plugins and the default layout and store.

**Comment by shubhra14** [comment]
Looking forward to it, thank you!
